import React, { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, CheckCircle, XCircle } from 'lucide-react'
import { useTheme } from '@/hooks/useTheme'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { spacing, typography } from '@/styles/tokens'
import { generatePractice, evaluatePractice } from '@/lib/api'

interface Question { id: number; question_text: string; concept?: string; difficulty?: string }
export const Practice: React.FC = () => {
  const { colors } = useTheme(); const [questions, setQuestions] = useState<Question[]>([]); const [current, setCurrent] = useState(0); const [answer, setAnswer] = useState(''); const [result, setResult] = useState<{is_correct: boolean; feedback: string} | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { setQuestions(await generatePractice(undefined, 3)); setCurrent(0); setAnswer(''); setResult(null) } catch (e) { setError(e instanceof Error ? e.message : 'Could not generate practice') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const q = questions[current]
  const submit = async () => { if (!q || !answer.trim()) return; try { setResult(await evaluatePractice(q.id, answer.trim())) } catch (e) { setError(e instanceof Error ? e.message : 'Could not evaluate answer') } }
  const next = () => { if (current < questions.length - 1) { setCurrent(current + 1); setAnswer(''); setResult(null) } else load() }
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ padding: spacing[4], maxWidth: 900, margin: '0 auto' }}>
    <div style={{ marginBottom: spacing[5] }}><h1 style={{ fontSize: typography.sizes['3xl'], color: colors.textPrimary }}>Practice Questions</h1><p style={{ color: colors.textSecondary }}>Questions are generated by the backend and evaluated with the same AI service.</p></div>
    {error && <div style={{ color: colors.error, marginBottom: spacing[3] }}>{error}</div>}
    {loading ? <Card padding={5}><p style={{ color: colors.textSecondary }}>Generating questions…</p></Card> : q ? <Card padding={5}><div style={{ color: colors.textMuted, marginBottom: spacing[2] }}>Question {current + 1} / {questions.length} · {q.difficulty || 'mixed'}</div><h2 style={{ fontSize: typography.sizes['2xl'], color: colors.textPrimary, lineHeight: 1.5, marginBottom: spacing[4] }}>{q.question_text}</h2><Input value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Type your answer" fullWidth disabled={!!result} />{result && <div style={{ marginTop: spacing[3], padding: spacing[3], borderRadius: 10, background: result.is_correct ? `${colors.success}20` : `${colors.error}20`, color: colors.textPrimary, display: 'flex', gap: spacing[2] }}>{result.is_correct ? <CheckCircle color={colors.success} /> : <XCircle color={colors.error} />}<span>{result.feedback}</span></div>}<div style={{ marginTop: spacing[4] }}>{result ? <Button onClick={next} fullWidth>{current < questions.length - 1 ? 'Next Question' : 'Generate More'} <ArrowRight size={18} /></Button> : <Button onClick={submit} fullWidth disabled={!answer.trim()}>Check Answer</Button>}</div></Card> : <Card padding={5}><Button onClick={load}>Generate Practice</Button></Card>}
  </motion.div>
}
